### ISSUE TITLE
When user logged in, they will be directed to landing page

### ISSUE THREAD

**Issue by croml** [feyclan/WT_backend#18]
This is the first page the user will see.
This page is an overview of the available books.

**Comment by croml** [comment]
When the user (trainee) logs in the application, it's landing page should be the catalogue. In this catalogue the user should be able to see which books are avaiable.

**Comment by vsshu** [comment]
Trainees are now directed to the 'catalogus' page upon login. This page allows them to search for books and view an overview of available books.

Trainers are redirected to the 'home' page after logging in. Note: the 'home' page is currently empty, future dashboards are in mind
