### ISSUE TITLE
Catalogue trainers: expanding search bar

### ISSUE THREAD

**Issue by croml** [feyclan/WT_backend#24]
momenteel kan je wel zoeken op boektitel, maar dit willen we uitbreiden naar auteur, beschrijving/tags, ISBN

**Comment by iKerolos** [comment]
- Modified the `SearchBookDto` class to include a searchTerm field along with its getter and setter methods. This field represents the single search term entered by the user.
- Updated the `searchBooks` method in the backend service to utilize the searchTerm for searching books based on title, authors' names, and descriptions simultaneously.
- Implemented a Specification to construct the query dynamically, combining conditions for title, authors, and description using logical OR operations.
