### ISSUE TITLE
Make rules on how to make new branching

### ISSUE THREAD

**Issue by croml** [feyclan/WT_backend#41]

**Comment by croml** [comment]
Documentation will be set in DoD

**Comment by iKerolos** [comment]
When naming branch names, we adopt the format `Category-ticketnumber` to ensure clarity and traceability. Here are the guidelines for each category:

1. **hotfix-TICKETNUMBER**: Use this for branches aimed at quickly addressing critical issues, typically with temporary solutions. This is reserved for urgent fixes that can't wait for a regular update cycle.

2. **bugfix-TICKETNUMBER**: This is used for branches where the focus is on fixing bugs. This category helps in tracking the correction of specific faults or errors in the system.

3. **feature-TICKETNUMBER**: Employ this for branches involved in adding, removing, or modifying features. This category is broad, encompassing any enhancement or change to existing functionalities.

4. **test-TICKETNUMBER**: Use this category for experimental branches where the changes are not meant to address an existing issue. This could be for testing new theories, tools, or methods.

5. **wip-TICKETNUMBER**: This stands for 'Work In Progress'. It is used for ongoing development that may not yet be ready for testing or release. This tag helps in identifying branches that are in the early stages of development.

By adhering to these naming conventions, we enhance our ability to manage versions and track changes efficiently across our projects.
